"""correção na vinculação das tabelas (FK)

Revision ID: 0aa9d6e66c22
Revises: fcf1f7b68d5a
Create Date: 2024-06-09 11:12:55.390189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa9d6e66c22'
down_revision = 'fcf1f7b68d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'service', ['service_id'], ['service_id'])

    with op.batch_alter_table('flow', schema=None) as batch_op:
        batch_op.drop_constraint('flow_service_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('flow_service_id_fkey', 'service', ['service_id'], ['service_id'])

    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
