"""Adição a tabela step e separação da lógica do flow

Revision ID: dd3d270aa380
Revises: 0aa9d6e66c22
Create Date: 2024-06-11 19:39:52.225592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd3d270aa380'
down_revision = '0aa9d6e66c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.agent_id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.flow_id'], ),
    sa.PrimaryKeyConstraint('step_id')
    )
    with op.batch_alter_table('flow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('flow_agent_id_fkey', type_='foreignkey')
        batch_op.drop_column('step_number')
        batch_op.drop_column('instructions')
        batch_op.drop_column('agent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('instructions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('flow_agent_id_fkey', 'agent', ['agent_id'], ['agent_id'])
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    op.drop_table('step')
    # ### end Alembic commands ###
