"""insert input_schema, output_schema on service

Revision ID: fcf1f7b68d5a
Revises: 3a386a111c13
Create Date: 2024-05-25 14:15:30.706652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf1f7b68d5a'
down_revision = '3a386a111c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_schema', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('output_schema', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('output_schema')
        batch_op.drop_column('input_schema')

    # ### end Alembic commands ###
